export const FUNCTIONAL_AREAS: string[] = [
  "Accommodation",
  "Accreditation and Access Control",
  "Activities & Events",
  "Administration",
  "Arrivals & Departures",
  "Asian Games Mascot",
  "Brand Identity and Look of the Games",
  "Broadcast Integration",
  "Ceremonies",
  "City Operations",
  "Cleaning & Waste",
  "Communications",
  "Culture & Education",
  "Doping Control",
  "Energy",
  "Event Services",
  "Finance",
  "Food & Beverage",
  "Games Family Services & Protocol",
  "Games Workforce and Volunteers",
  "Hospitality",
  "Information, Knowledge and Games Learning",
  "Language Services",
  "Legal",
  "Licensing and Merchandising",
  "Logistics",
  "Marketing Partner Services",
  "Media and News",
  "Medical Services",
  "NOC/NPC Services",
  "Para Asian Integration",
  "Planning and Integration",
  "Press Operations",
  "Procurement",
  "Results, Timing and Scoring",
  "Rights Protection",
  "Security",
  "Sponsorship",
  "Sport Competition",
  "Sport Planning and Operations",
  "Sport Presentation",
  "Sustainability, Impact and Legacy",
  "Technology & Information Systems",
  "Ticketing",
  "Torch Relay",
  "Transport",
  "Uniforms",
  "Venue Management",
  "Venue Technology",
  "Venues & Infrastructure",
  "Village Management",
];
